---
# Script to Boostrap a New Fedora System

- hosts: localhost
  vars:
    fedora_release_version: 36
  tasks:
    - import_tasks: tasks/essential.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/dev-tools.yml
    - import_tasks: tasks/npm.yml
    - import_tasks: tasks/rustup.yml
    - import_tasks: tasks/productivity.yml
    - import_tasks: tasks/virtualization.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/sublime-text.yml
    - import_tasks: tasks/1password.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/fish.yml
    - import_tasks: tasks/fonts.yml
